name: u-root-builder

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    strategy:
      matrix:
        template: [core, all, embedded, minimal]
        arch: [amd64, arm, arm64, riscv64]

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        repository: u-root/u-root

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: |
        go build .
        GOARCH=${{ matrix.arch }} ./u-root -uroot-source . -o u-root-${{ matrix.arch }}-${{ matrix.template }}.cpio ${{ matrix.template }}

    - name: Upload
      uses: actions/upload-artifact@v3.1.3
      with:
        path: u-root-${{ matrix.arch }}-${{ matrix.template }}.cpio
